package com.lining.boot.mapper;

import com.lining.boot.model.Province;
import com.lining.boot.model.ProvinceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated Mon May 14 15:48:59 GMT+08:00 2018
     */
    long countByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated Mon May 14 15:48:59 GMT+08:00 2018
     */
    int deleteByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated Mon May 14 15:48:59 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated Mon May 14 15:48:59 GMT+08:00 2018
     */
    int insert(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated Mon May 14 15:48:59 GMT+08:00 2018
     */
    int insertSelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated Mon May 14 15:48:59 GMT+08:00 2018
     */
    List<Province> selectByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated Mon May 14 15:48:59 GMT+08:00 2018
     */
    Province selectByPrimaryKey(Long areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated Mon May 14 15:48:59 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Province record, @Param("example") ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated Mon May 14 15:48:59 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Province record, @Param("example") ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated Mon May 14 15:48:59 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_province
     *
     * @mbg.generated Mon May 14 15:48:59 GMT+08:00 2018
     */
    int updateByPrimaryKey(Province record);
}